version: '3'

services:
  drone-agent:
    image: drone/agent:1.0.0-rc.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=${DRONE_RPC_SERVER}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_LOGS_DEBUG=true
      - DRONE_RUNNER_CAPACITY=4
      - DRONE_RUNNER_NAME=10.0.0.2
    restart: always